import { AmazonCategory, AmazonDatabaseItems } from '../../../shared/interfaces/amazon-items';
export const AMAZON_DATABASE_SEARCH_ITEMS: AmazonDatabaseItems = {
  categories: [],
  minPrice: null,
  maxPrice: null,
  minReviews: null,
  maxReviews: null,
  minRating: null,
  maxRating: null,
  minSalesPerMonth: null,
  maxSalesPerMonth: null,
  minRevenuePerMonth: null,
  maxRevenuePerMonth: null,
  minAmazonSellerRank: null,
  maxAmazonSellerRank: null,
  minNumberOfSellers: null,
  maxNumberOfSellers: null,
  minProfit: null,
  maxProfit: null,
  minQualityScore: null,
  maxQualityScore: null,
  sellerType: [],
  titleKeyword: '',
  sortField: '',
  direction: 'asc',
  excludeTitleKeywords: '',
  brand: '',
  page: null
};

export const AMAZON_ITEM_CATEGORIES: AmazonCategory[] = [
  { value: 'aps', label: 'All Departments' },
  { value: 'Appliances', label: 'Appliances' },
  { value: 'Arts, Crafts & Sewing', label: 'Arts, Crafts & Sewing' },
  { value: 'Automotive Parts & Accessories', label: 'Automotive Parts & Accessories' },
  { value: 'Baby Products', label: 'Baby Products' },
  { value: 'Baby', label: 'Baby' },
  { value: 'Beauty & Personal Care', label: 'Beauty & Personal Care' },
  { value: 'Books', label: 'Books' },
  { value: 'Cell Phones & Accessories', label: 'Cell Phones & Accessories' },
  { value: 'Clothing, Shoes & Jewelry', label: 'Clothing, Shoes & Jewelry' },
  { value: 'Collectibles & Fine Art', label: 'Collectibles & Fine Art' },
  { value: 'Electronics', label: 'Electronics' },
  { value: 'Grocery & Gourmet Food', label: 'Grocery & Gourmet Food' },
  { value: 'Health, Household & Baby Care', label: 'Health, Household & Baby Care' },
  { value: 'Home & Kitchen', label: 'Home & Kitchen' },
  { value: 'Industrial & Scientific', label: 'Industrial & Scientific' },
  { value: 'Luxury Beauty', label: 'Luxury Beauty' },
  { value: 'Musical Instruments', label: 'Musical Instruments' },
  { value: 'Office products', label: 'Office products' },
  { value: 'Patio, Lawn & Garden', label: 'Patio, Lawn & Garden' },
  { value: 'Pet Supplies', label: 'Pet Supplies' },
  { value: 'Software', label: 'Software' },
  { value: 'Sports & Outdoors', label: 'Sports & Outdoors' },
  { value: 'Tools & Home Improvement', label: 'Tools & Home Improvement' },
  { value: 'Toys & Games', label: 'Toys & Games' },
  { value: 'Video Games', label: 'Video Games' }
];

export const AMAZON_SELLER_TYPE = ['AMZ', 'FBA', 'FBM'];
